### ISSUE TITLE
Parse McGill-Billboard dataset

### ISSUE THREAD

**Issue by pianobin** [SIGMusic/musicMaker-backend#1]
Parse the data from McGill-Billboard/annotations into Python objects we can analyze. The objects should store the chords sequentially

See: http://www.cs.uu.nl/research/techreps/repo/CS-2012/2012-018.pdf

**Comment by sahilshahpatel** [comment]
Things we still need to do:

- Need to account for meter.
	> Detect chords by ':' instead, and used the '|' to detect duration
	> Chords are flanked by spaces ALWAYS
- Account for dots
	> If a chord is repeated within a beat, it is denoted with a '.'
	> See 0006
- Account for repetition counters
	> At the end of a line (after the last '|'), there can be a "xN" indicator. Use this to change the duration of the whole last line
	> See 0006
- Account for weird 'N' chords
	> Might be solved by detecting ':'
	> See "Song Number 55:"
- Account for weird fractions
	> See "Song Number 56:"
	> Not sure what they mean, but they look like "| (3/4) C:min |"

**Comment by pianobin** [comment]
> Things we still need to do:
> 
>     * Need to account for meter.
>       > Detect chords by ':' instead, and used the '|' to detect duration
>       > Chords are flanked by spaces ALWAYS
> 
>     * Account for dots
>       > If a chord is repeated within a beat, it is denoted with a '.'
>       > See 0006
> 
>     * Account for repetition counters
>       > At the end of a line (after the last '|'), there can be a "xN" indicator. Use this to change the duration of the whole last line
>       > See 0006
> 
>     * Account for weird 'N' chords
>       > Might be solved by detecting ':'
>       > See "Song Number 55:"
> 
>     * Account for weird fractions
>       > See "Song Number 56:"
>       > Not sure what they mean, but they look like "| (3/4) C:min |"

Feel free to make these into separate issues if these are too many tasks

**Comment by sahilshahpatel** [comment]
Parser has been completed. It scans the McGill-Billboard directory and returns a 3D list of pychord.Chord's with dimensions (song, section, chord).
