### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by pianobin** [SIGMusic/musicMaker-backend#15]
Explain to newcomers how to get setup and contribute to the project. Should include:

- [ ] Prerequisites
- [ ] Setup Guide
- [ ] Explanation of Codebase structure
- [ ] How to fork/branch and make a pull request

**Comment by melissachen2000** [comment]
Resolved in f4efa1919758ae91e3338ba94e63dd46dd1cd0db
